### ISSUE TITLE
database restore fail

### ISSUE THREAD

**Issue by shindoujay** [pauloamgomes/generator-docker4drupal#1]
docker: Version 2.0.0.0-mac81 (29211)
OS:  macOS 10.14.1 (18B75)

`$ ./sj3d.sh db-restore --file=./docroot/web/sj3d-2018-12-10-19-59-51.sql`
` sj3d.sh command helper for sj3d`

`Restoring mysql dump:`
 `14M    ./docroot/web/sj3d-2018-12-10-19-59-51.sql`

`Please wait, it can take some minutes...`

`ERROR 1227 (42000) at line 18: Access denied; you need (at least one of) the SUPER privilege(s) for this operation`
`Done!`

**Comment by pauloamgomes** [comment]
do you have your settings.php configured properly? Confirm that you have a settings.local.php in sites/default and its identical to the one provided in docker/examples/ folder
